#@data/values
---
name: dev-briq-api
env: test
storage_bucket: briq-bucket-test-1
static_ip: lb-sltech-company-ipv4-3
sites: ["api.test.sltech.company"]
log_level: "DEBUG"

#@schema/type any=True
defaultLabels:
  appname: dev-briq
  env: test

set_indexer_network_name: starknet-testnet-dojo

indexer:
  name: dev-briq-indexer
  image_store: mongo:latest
  indexer_ids: ["dojo-3", "testnet-legacy-0"]
  network_names: ["starknet-testnet-dojo", "starknet-testnet"]
